### ISSUE TITLE
Find better repo name

### ISSUE THREAD

**Issue by DrWenz** [AvaloniaInside/SystemManager#7]
Suggestions:
- AvaloniaInside.Core
- AvaloniaInside.CoreControl
- AvaloniaInside.Base

**Comment by DrWenz** [comment]
- LinuxHelper
- LinuxUtility

**Comment by OmidID** [comment]
AvaloniaInside.Utilitix

**Comment by OmidID** [comment]
AvaloniaInside.SystemManager or AvaloniaInside.LinuxManager

**Comment by DrWenz** [comment]
> AvaloniaInside.SystemManager or AvaloniaInside.LinuxManager

I like AvaloniaInside.SystemManager

**Comment by DrWenz** [comment]
Renamed to SystemManager
